### ISSUE TITLE
Not all records have a NameIdentifier

### ISSUE THREAD

**Issue by tgbugs** [Pennsieve/doi-service#4]
RE: https://github.com/Pennsieve/pennsieve-api/issues/85

I don't know enough scala to be sure, but I think that the json parser is encountering a case where a field that the code says is non-optional field is in reality missing and so it barfs.

`The field [.data.attributes.contributors[0].nameIdentifiers[0].nameIdentifier] is missing.`

https://github.com/Pennsieve/doi-service/blob/cbad1be1599f16a1d2fdae267c4302a745265ed5/common/src/main/scala/com/blackfynn/doi/models/DataciteDoi.scala#L12
https://github.com/Pennsieve/doi-service/blob/cbad1be1599f16a1d2fdae267c4302a745265ed5/common/src/main/scala/com/blackfynn/doi/models/DataciteDoi.scala#L74

**Comment by jwagenaar** [comment]
The platform requires the corresponding contributor to have an ORCID ID. This is optional for other authors in the dataset. The API error you were seeing is related to a legacy datacite record which was created before this was enforced.
